name: Vespa Schema LSP - Deploy extension

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        descirption: Which kind of release is this
        required: true
        options:
          - major
          - minor
          - patch
  push:
    branches:
      - interns/languageserver

jobs:

  lspDeploy:
    name: Vespa Schema LSP Deployment Job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Vespa
        run: |
          export MAVEN_OPTS="-Xms128m -Xmx1024m"
          ./bootstrap.sh java
          mvn install --threads 1C
        working-directory: ./

      - uses: actions/setup-node@v4
        with:
          node-version: 20
        
      - name: Download node dependencies
        run: npm ci
        working-directory: ./integration/schema-language-server/clients/vscode

      - name: Publish VScode extension
        run: npm run publish
        working-directory: ./integration/schema-language-server/clients/vscode
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
      
      # - name: Publish Intellij plugin
      #   run: gradle publishPlugin
      #   working-directory: ./integration/schema-language-server/clients/intellij
      #   env:
      #     CERTIFICATE_CHAIN: ${{ secrets.INTELLIJ_CERTIFICATE_CHAIN }}
      #     PRIVATE_KEY: ${{ secrets.INTELLIJ_PRIVATE_KEY }}
      #     PRIVATE_KEY_PASSWORD: ${{ secrets.INTELLIJ_PRIVATE_KEY_PASSWORD }}
      #     PUBLISH_TOKEN: ${{ secrets.INTELLIJ_PUBLISH_TOKEN }}
      
      - name: Create PR to bump version
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update Vespa Language Server VSCode extension version"
          title: "Bump Vespa Language Server version"
          body: "This PR updates the Vespa Language Server VSCode extension"
          branch: "interns/languageserver-bump-version"
          base: "master"
          labels: "Language server"
