name: Vespa Schema LSP - Deploy extension

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Which kind of release is this
        required: true
        options:
          - major
          - minor
          - patch

jobs:

  lspDeploy:
    name: Vespa Schema LSP Deployment Job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Vespa
        run: |
          export MAVEN_OPTS="-Xms128m -Xmx1024m"
          ./bootstrap.sh java
          mvn install --threads 1C
        working-directory: ./

      - uses: actions/setup-node@v4
        with:
          node-version: 20
        
      - name: Download node dependencies
        run: npm ci
        working-directory: ./integration/schema-language-server/clients/vscode

      - name: Publish VScode extension
        run: npm run publish
        working-directory: ./integration/schema-language-server/clients/vscode
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Publish IntelliJ plugin
        run: |
          python3 bumpVersion.py
          gradle buildPlugin
          curl -i --header "Authorization: Bearer $INTELLIJ_PLUGIN_PERM" -F pluginId=$PLUGIN_ID -F file=./build/distributions/vespa-$(cat VERSION).zip https://plugins.jetbrains.com/plugin/uploadPlugin
        working-directory: ./integration/schema-language-server/clients/intellij
        env:
          INTELLIJ_PLUGIN_PERM: ${{ secrets.INTELLIJ_PLUGIN_PERM }}
          PLUGIN_ID: 18074
      
      - name: Create PR to bump version
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update Vespa Language Server VSCode extension version"
          title: "Bump Vespa Language Server version"
          body: "This PR updates the Vespa Language Server VSCode extension"
          branch: "interns/languageserver-bump-version"
          base: "master"
          labels: "Language server"
